baseURL = "https://tbueno.github.io/camp/"
title = "Camp"
theme = ["docsy"]

# Module configuration for npm packages (PostCSS mode)
[module]
  proxy = "direct"
  # Mount project directories
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  # Mount Bootstrap and Font Awesome from node_modules
  [[module.mounts]]
    source = "node_modules/bootstrap"
    target = "assets/vendor/bootstrap"
  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free"
    target = "assets/vendor/Font-Awesome"
  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Useful when translating
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

# Configure how URLs look
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Language configuration
[languages]
[languages.en]
title = "Camp"
description = "Your all-in-one development environment manager"
languageName ="English"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

# Everything below this are Site Params

[params]
copyright = "The Camp Authors"
privacy_policy = ""

# Repository configuration (for "Edit this page" links)
github_repo = "https://github.com/tbueno/camp"
github_project_repo = "https://github.com/tbueno/camp"
github_branch = "main"

# Search configuration
[params.search]
# Enable local offline search (works without external dependencies)
offlineSearch = true

# Algolia DocSearch (optional, free for open source)
# [params.search.algolia]
# appId = "YOUR_APP_ID"
# apiKey = "YOUR_API_KEY"
# indexName = "YOUR_INDEX_NAME"

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state
sidebar_menu_compact = true
# Show expand/collapse icon for sidebar sections
sidebar_menu_foldable = true
# https://github.com/google/docsy/pull/184
sidebar_cache_limit = 10
# Enable breadcrumb navigation
breadcrumb_disable = false
# Enable the "about" section in footer
footer_about_enable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
[params.ui.feedback]
enable = false

# Adds a reading time to the top of each doc.
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "GitHub Discussions"
	url = "https://github.com/tbueno/camp/discussions"
	icon = "fab fa-github"
  desc = "Discussion and help from the community"
[[params.links.user]]
	name = "GitHub Issues"
	url = "https://github.com/tbueno/camp/issues"
	icon = "fab fa-github"
  desc = "Report bugs or request features"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/tbueno/camp"
	icon = "fab fa-github"
  desc = "Development takes place here!"

# Version menu configuration (disable for now, enable when you have multiple versions)
# [params.versions]
# version_menu = "Versions"
# [[params.versions.list]]
#   version = "main (development)"
#   url = "https://tbueno.github.io/camp/"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Documentation"
    weight = 10
    url = "/docs/"
  [[menu.main]]
    name = "Blog"
    weight = 20
    url = "/blog/"
  [[menu.main]]
    name = "GitHub"
    weight = 30
    url = "https://github.com/tbueno/camp"
